INFO - Bubble Sort - Running command 'bubbleSort'
INFO - Bubble Sort - Started run with ID "236"
Experiment: Bubble Sort Experiment



Bubble Sort Experiment is running for 10 seconds!


Default timeout bound exceeded! Default timeout after 5sec.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/julius/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/julius/anaconda3/lib/python3.5/threading.py", line 1180, in run
    self.function(*self.args, **self.kwargs)
  File "/home/julius/anaconda3/lib/python3.5/site-packages/sacred/run.py", line 266, in _start_heartbeat
    self._emit_heartbeat()
  File "/home/julius/anaconda3/lib/python3.5/site-packages/sacred/run.py", line 339, in _emit_heartbeat
    result=self.result)
  File "/home/julius/anaconda3/lib/python3.5/site-packages/sacred/run.py", line 386, in _safe_call
    getattr(obs, method)(**kwargs)
  File "/home/julius/Dokumente/Uni/HPI/Jobs/GFZ/Sacred Test/timeout.py", line 61, in heartbeat_event
    self.expInstance.forceKill()
TypeError: forceKill() takes 0 positional arguments but 1 was given

