INFO - Bubble Sort - Running command 'bubbleSort'
WARNING - telegram.vendor.ptb_urllib3.urllib3.connectionpool - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x7f16280f8f60>, 'Connect timed out. (connect timeout=5.0)')': /bot350553078:AAEu70JDqMFcG_x5eBD3nqccTvc4aFNMKkg/sendMessage
INFO - Bubble Sort - Started run with ID "470"

Experiment: Bubble Sort Test Experiment

 cd /home/julius/Dokumente/Uni/HPI/Jobs/GFZ/SacredTest && python bubble.py bubblesort_input_dataset.csv reversed 
INFO - Bubble Sort - Completed after 0:00:10
